name: validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  find_renovate_config_files:
    name: Find Renovate configuration files
    outputs:
      files: ${{ steps.find-files.outputs.files }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: damoun/action-find-files@d0c8b39775242003138d0e125c527f12b5a82459 # v2
        id: find-files
        with:
          pattern: '.*json5?$'

  validate_renovate_config:
    name: Validate Renovate configuration
    needs: find_renovate_config_files
    strategy:
      matrix:
        file: ${{ fromJson(needs.find_renovate_config_files.outputs.files) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b54483862375f51910a60c4f498e927d4f3df466 # v1.0.1
        name: Run Renovate configuration validator
        with:
          config_file_path: ${{ matrix.file }}
